### ISSUE TITLE
(23) Failed writing body

### ISSUE THREAD

**Issue by MR-pentestGuy** [m4xx101/subash#2]
./subash.sh: line 23: $path_to_save: ambiguous redirect
(23) Failed writing body
./subash.sh: line 24: anew: command not found
./subash.sh: line 25: jq: command not found
./subash.sh: line 25: anew: command not found

**Comment by m4xx101** [comment]
Hey, Thanks for the info I forgot to add few tools in check-dependencies.sh, will add this!

**Comment by m4xx101** [comment]
Try new updated script!
