### ISSUE TITLE
findomain --file <files>... --target <target> --unique-output <unique-output ;;;Try 'rm --help' for more information

### ISSUE THREAD

**Issue by MR-pentestGuy** [m4xx101/subash#3]
error: The argument '--file <files>...' cannot be used with '--target <target>'

USAGE:
    findomain --file <files>... --target <target> --unique-output <unique-output>

For more information try --help
cat: invalid option -- 'f'
Try 'cat --help' for more information.
./subash.sh: line 29: anew: command not found
rm: invalid option -- 'n'
Try 'rm --help' for more information.

**Comment by m4xx101** [comment]
Hey can you share the snapshot exactly which parameters and commands you are giving as a input.

**Comment by MR-pentestGuy** [comment]
its okke bro i have done some changes . its really a good tool if you have any automation like that would plzz like to share it

**Comment by m4xx101** [comment]
Soon will release one more script which is custom wordlists generator according to the fed target!
